import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Tours Guide</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="bg-indigo-500">
                <h1 className="text-center text-blue-400">NEXT JS</h1>
                <div className="w-10 h-10 bg-green-500"></div>
            </div>
        </>
    )
}

export default Home
